name: Handle JSON Input

on:
  workflow_dispatch:
    inputs:
      jsonInput:
        description: 'JSON input'
        required: true
        default: '{"key1": "value1", "key2": "value2"}'

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print JSON Input
        run: echo "JSON Input: ${{ github.event.inputs.jsonInput }}"
      
      - name: Parse JSON Input with jq
        id: parse_json
        run: |
          echo '${{ github.event.inputs.jsonInput }}' | jq . >output.json
      - name: Display processed JSON
        run: cat output.json
      - name: Parse JSON Input with jq
        id: parse_json
        run: |
          echo '${{ github.event.inputs.jsonInput }}' | jq .
      
      - name: Access JSON Value
        run: |
          VALUE=$(echo '${{ github.event.inputs.jsonInput }}' | jq -r '.key1')
          echo "Value for key1: $VALUE"
