name: Write Input to JSON

on:
  workflow_dispatch:
    inputs:
      myTextInput:
        description: 'Text input to be written to JSON file'
        required: true
        default: 'default value'

jobs:
  write-to-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write input to JSON file
        run: |
          echo "{ \"${{ github.event.inputs.myTextInput }}\" > input.json

      - name: Show JSON content
        run: |
          cat input.json
